apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: configuser-configurer-binding
subjects:
  - kind: User
    name: configuser
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: configurer-role
  apiGroup: rbac.authorization.k8s.io